fix syntax

diff --git a/compress_pdf b/compress_pdf
--- a/compress_pdf
+++ b/compress_pdf
@@ -52,18 +52,18 @@ PAPER=a4    # Default Paper size
 # Parse arguments:
 # -----------------------------------------------------------------------------
 while [[ $1 == -* ]]; do
-    case $1 in
-        -h|--help|-\?) usage; exit 0;;
-        -d|--dpi) DPI=$2; shift 2;;
-        -s|--size) PAPER=$2; shift 2;;
-        --) shift; break;;
-        -*) echo "invalid option: $1" 1>&2; usage; exit 1;;
-    esac
+  case $1 in
+      -h|--help|-\?) usage; exit 0;;
+      -d|--dpi) DPI=$2; shift 2;;
+      -s|--size) PAPER=$2; shift 2;;
+      --) shift; break;;
+      -*) echo "invalid option: $1" 1>&2; usage; exit 1;;
+  esac
 done
 
 if [[ $# -lt 1 ]]; then usage; exit 0; fi
 inFile=$1   # Input File
-[ ! -f $inFile ] && echo -e "** ERROR: '$inFile' does not exist.\n" && exit 1
+[ ! -f "$inFile" ] && echo -e "** ERROR: '$inFile' does not exist.\n" && exit 1
 
 outFile="${2:-$(basename $inFile .pdf)-${DPI}dpi.pdf}"
 echo -e "Compressing to file: $outFile ... \c"
@@ -71,9 +71,11 @@ echo -e "Compressing to file: $outFile ... \c"
 # -----------------------------------------------------------------------------
 # Shrink PDF
 # -----------------------------------------------------------------------------
-gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dDownsampleColorImages=true \
-    -dColorImageResolution=$DPI -dNOPAUSE -dQUIET -dBATCH -sPAPERSIZE=$PAPER \
-    -sOutputFile=$outFile $inFile
+gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
+   -dDownsampleColorImages=true \
+   -dColorImageResolution="$DPI" \
+   -dNOPAUSE -dQUIET -dBATCH -sPAPERSIZE="$PAPER" \
+   -sOutputFile="$outFile" "$inFile"
 
 st=$?
 [[ "$st" -eq 0 ]] && echo -e "done." || exit "$st"
